// <auto-generated />
using System;
using India_Mart_Api;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace India_Mart_Api.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("India_Mart_Api.Model.CrmRecord", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CALL_DURATION")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("QUERY_MCAT_NAME")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("QUERY_MESSAGE")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("QUERY_PRODUCT_NAME")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("QUERY_TIME")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("QUERY_TYPE")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RECEIVER_CATALOG")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RECEIVER_MOBILE")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SENDER_ADDRESS")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SENDER_CITY")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SENDER_COMPANY")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SENDER_COUNTRY_ISO")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SENDER_EMAIL")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SENDER_EMAIL_ALT")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SENDER_MOBILE")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SENDER_MOBILE_ALT")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SENDER_NAME")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SENDER_PHONE")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SENDER_PHONE_ALT")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SENDER_PINCODE")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SENDER_STATE")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SUBJECT")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UNIQUE_QUERY_ID")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("CrmRecords");
                });
#pragma warning restore 612, 618
        }
    }
}
